version: 0.2
env:
  variables:
    PRX_ECR_REGION: "us-east-1"
    PRX_ECR_REPOSITORY: "metrics.prx.org"
    PRX_ECR_CONFIG_PARAMETERS: "MetricsEcrImageTag"
phases:
  install:
    commands:
      - 'echo "Installing docker-compose..."'
      - 'COMPOSE="https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" && curl -sL $COMPOSE -o /usr/local/bin/docker-compose'
      - "chmod +x /usr/local/bin/docker-compose"
  build:
    commands:
      - "docker-compose -f docker-compose.yml build"
      - "docker-compose -f docker-compose.yml run metrics testonce"
  post_build:
      commands:
        - 'curl -sO "https://raw.githubusercontent.com/PRX/Infrastructure/master/ci/utility/post_build.sh" && chmod +x post_build.sh && bash ./post_build.sh'
