metrics:
  build: .
  volumes:
    - ./bin:/app/bin
    - ./e2e:/app/e2e
    - ./src:/app/src
  env_file:
    - .env
  ports:
    - "4202:4202"
  command: start
  environment:
    VIRTUAL_HOST: metrics.prx.docker
    HOST: http://publish.prx.docker
