import { Action } from '@ngrx/store';

export const ActionTypes = {
  CMS_PODCASTS: 'CMS_PODCASTS',
  CMS_PODCASTS_SUCCESS: 'CMS_PODCASTS_SUCCESS',
  CMS_PODCASTS_FAILURE: 'CMS_PODCASTS_FAILURE',
  CMS_EPISODE_GUID: 'CMS_EPISODE_GUID',
  CMS_ALL_PODCAST_EPISODE_GUIDS: 'CMS_ALL_PODCAST_EPISODE_GUIDS',
  CASTLE_PODCAST_METRICS: 'CASTLE_PODCAST_METRICS',
  CASTLE_EPISODE_METRICS: 'CASTLE_EPISODE_METRICS',
  CASTLE_FILTER: 'CASTLE_FILTER'
};

export interface ActionWithPayload<T> extends Action {
  payload: T;
}
