export const ActionTypes = {
  CMS_PODCASTS: 'CMS_PODCASTS',
  CMS_ALL_PODCAST_EPISODE_GUIDS: 'CMS_ALL_PODCAST_EPISODE_GUIDS',
  CASTLE_PODCAST_METRICS: 'CASTLE_PODCAST_METRICS',
  CASTLE_EPISODE_METRICS: 'CASTLE_EPISODE_METRICS',
  CASTLE_FILTER: 'CASTLE_FILTER',
  GOOGLE_ANALYTICS_EVENT: 'GOOGLE_ANALYTICS_EVENT'
};
